### ISSUE TITLE
Offline list not firing subscriptions on push

### ISSUE THREAD

**Issue by tja4472** [adriancarriger/angularfire2-offline#55]
### internal-list-observable.ts
Replace
```typescript
this.previousValue = this.newValue;
```
with
```typescript
this.previousValue = Object.assign([], newValue);
```

```typescript
  uniqueNext(newValue) { 
    // Sort
    if (this.previousValue) { this.previousValue.sort((a, b) => a.$key - b.$key); }
    if (newValue) { newValue.sort((a, b) => a.$key - b.$key); }
 
    if (this.updated > 1 || (stringify(this.previousValue) !== stringify(newValue)) ) {
      this.previousValue = Object.assign([], newValue); //<====
      this.next(newValue);
      this.updated++;
    }
  }
```

hth
Tim

**Comment by adriancarriger** [comment]
Hi @tja4472, this should be fixed in version 4.2.2 and looks related to issue #46. Let me know if it's different and still present. Thanks! 👍

**Comment by tja4472** [comment]
Hi @adriancarriger 

I'm afraid it's still present.

### write-list.component.ts
```typescript
export class WriteListComponent {
  groceries: AfoListObservable<any[]>;
  constructor(private afoDatabase: AngularFireOfflineDatabase) {
    this.groceries = this.afoDatabase.list('/groceries');

    this.groceries.subscribe(x => {
      console.log('this.groceries.subscribe', x);
    });
  }
```
If you go offline then run the example the subscribe only gets called once. 

Does not get called when adding items.

**Comment by adriancarriger** [comment]
Hi @tja4472, thanks for the example!

* I've put it into [a demo](https://adriancarriger.github.io/angularfire2-offline/issues/55.1/dist/) (with [code](https://github.com/adriancarriger/angularfire2-offline/blob/gh-pages/issues/55.1/src/app/app.component.ts#L19-L21)) and I can confirm that `subscribe` is only being triggered while online
* An interesting thing is that while offline the items still show up in the UI

I'll be taking a look at this in greater detail soon!

**Comment by adriancarriger** [comment]
Hi @tja4472, this is now fixed in version 4.2.3. [Your code change](https://github.com/adriancarriger/angularfire2-offline/commit/a8760d4c0991fa3c52798ca86184e81f2b4cb640) fixed it! Thank you! 🎉 🎉 🎉

Here is the [updated demo](https://adriancarriger.github.io/angularfire2-offline/issues/55.2/dist/) which now correctly triggers the `.subscribe` for pushes to lists while offline.

Thanks! 👍

**Comment by AhabweEmmanuel** [comment]
Hi everyone, this issue is still there. Am using version 4.3.1. When the app starts offline, nothing displays until I connect to the internet. Thanks alot for any help in advance
